// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function CombineImages(framePath: string, screenshotPath: string): $CancellablePromise<string> {
    return $Call.ByID(3852145585, framePath, screenshotPath);
}

export function ImagePreview(path: string): $CancellablePromise<string> {
    return $Call.ByID(1896369581, path);
}
