// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * 設定目前要在前端預覽的外框圖片，回傳的 URL 可直接指定給 <img src>
 * 
 * 參數:
 *   - path: 圖片檔案路徑（相對或絕對路徑）
 * 
 * 回傳:
 *   - url: 前端可用的虛擬 URL（例如 "/media/image/frame.png?v=123"）
 *   - error: 若路徑無效或檔案不存在則回傳錯誤
 */
export function SetFramePath(path: string): $CancellablePromise<string> {
    return $Call.ByID(955951932, path);
}

/**
 * 設定目前要在前端預覽的截圖圖片，回傳的 URL 可直接指定給 <img src>
 * 
 * 參數:
 *   - path: 圖片檔案路徑（相對或絕對路徑）
 * 
 * 回傳:
 *   - url: 前端可用的虛擬 URL（例如 "/media/image/screenshot.png?v=123"）
 *   - error: 若路徑無效或檔案不存在則回傳錯誤
 */
export function SetScreenshotPath(path: string): $CancellablePromise<string> {
    return $Call.ByID(1180299829, path);
}
