// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * 設定目前允許 WebView 播放的影片；回傳固定的虛擬 URL；前端不可自行指定本機檔案路徑
 * 
 * 參數:
 *   - path: 影片檔案路徑（相對或絕對路徑）
 * 
 * 回傳:
 *   - url: 前端可用的虛擬 URL（例如 "/media/video/input.mp4?v=123"）
 *   - error: 若路徑無效或檔案不存在則回傳錯誤
 */
export function SetVideoPath(path: string): $CancellablePromise<string> {
    return $Call.ByID(2904380044, path);
}
